package:
    name: geneviz
    version: 0.1.0.dev0

source:
    path: ../

build:
    number: 0
    skip: False

requirements:
    build:
        - future >=0.15
        - pandas >=0.18.1
        - matplotlib >=1.5
        - pysam >=0.9.1
        - toolz >=0.8.0
        - intervaltree >=2.1.0
        - seaborn >=0.7

    run:
        - future >=0.15
        - pandas >=0.18.1
        - matplotlib >=1.5
        - pysam >=0.9.1
        - toolz >=0.8.0
        - intervaltree >=2.1.0
        - seaborn >=0.7

test:
    imports:
        - geneviz

    commands:
        - py.test $SRC_DIR

    requires:
        - pytest >=2.9
        - pytest-helpers-namespace

about:
    home: https://github.com/jrderuiter/geneviz
    license: MIT
    summary: "Python library for creating visualizations of genomic data."
